### ISSUE TITLE
Can you rework this example to use flexbox instead of grids?

### ISSUE THREAD

**Issue by chrzrdx** [VenkatPantham/edyst-s19-choose-a-pokemon#4]
https://github.com/VenkatPantham/edyst-s19-choose-a-pokemon/blob/f9494eae7b729c3f07cd44ac2044f319a37275f9/frontend/index.html#L61

If not, add some comments that explain the grid syntax you have used here.

**Comment by VenkatPantham** [comment]
Done with flexbox
